package com.dev21.program;

public enum SyntaxKind {
    NUMBER_TOKEN,
    ADDITION_TOKEN,
    SUBTRACTION_TOKEN,
    MULTIPLICATION_TOKEN,
    DIVISION_TOKEN,
    OPEN_PARENTHESIS_TOKEN,
    CLOSE_PARENTHESIS_TOKEN,
    BAD_TOKEN,
    END_OF_FILE_TOKEN,

    UNARY_EXPRESSION,
    BINARY_EXPRESSION,
    PARENTHESIZED_EXPRESSION,
    LITERAL_EXPRESSION
}
